[package]
name = "big-int-proc"
version = "1.2.0"
edition = "2021"
author = "Maurdekye"
description = "Proc macros for `big-int`."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.43"
